TRUNCATE TABLE Q_Asset_Inventory;
TRUNCATE TABLE Q_Asset_Inventory_Software_AssetId;
TRUNCATE TABLE Q_Asset_Inventory_Software_OS_Unique;
TRUNCATE TABLE software_pre_eol_eos;
TRUNCATE TABLE software_instance_count;